Sylius\Component\Locale\Model\Locale:
    exclusion_policy: ALL
    xml_root_name: locale
    relations:
        - rel: self
          href:
                route: sylius_admin_api_locale_show
                parameters:
                    code: expr(object.getCode())
                    version: 1
