Sylius\Component\Currency\Model\ExchangeRate:
    exclusion_policy: ALL
    xml_root_name: exchange_rate
    relations:
        - rel: self
          href:
            route: sylius_admin_api_exchange_rate_show
            parameters:
                sourceCurrencyCode: expr(object.getSourceCurrency().getCode())
                targetCurrencyCode: expr(object.getTargetCurrency().getCode())
                version: 1
            exclusion:
                groups: [Default, Detailed]
